# Makefile

CXX = g++
CXXFLAGS = -Wall -Iinclude


SOURCES = main.cpp ComplexNumber.cpp SortComplex.cpp
EXECUTABLE = main


all:
	$(CXX) $(CXXFLAGS) $(SOURCES) -o $(EXECUTABLE)


clean:
	rm -f $(EXECUTABLE)
